name: "CICD Pipeline Demo - Dummy Application"
on: workflow_dispatch

jobs:
    ContinuousIntegration:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code from repository
              uses: actions/checkout@v3
            - name: Setup python environment for exeuting script 
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"
  
              
    SonarQubeScan:
        needs: ContinuousIntegration
        runs-on: ubuntu-latest
        steps:
            - name: Setup Sonarqube
              run: echo "Setting up sonarqube server"
            - name: Scan and save outcomes
              run: echo "running scans"
              
    
    Build:
        needs: SonarQubeScan
        runs-on: ubuntu-latest
        steps:
            - name: Build Python application 
              run: echo "building application"
              
    SaveArtifact:
        needs: Build
        runs-on: ubuntu-latest
        steps:
            - name: Push artifact to Nexus (Example)
              run: echo "Saving artifacts"
    
    Deploy:
        needs: SaveArtifact
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Target
              run: echo "Doing deployments"
              
      
